# Settings 
DELAY_1 = 0
DELAY_2 = 0
DELAY_3 = 0
DELAY_4 = 40
DELAY_0 = 0

TRIGG_CH = 8
DET_CH1 = 1
DET_CH2 = 2
DET_CH3 = 3


DELAYS = [DELAY_0, DELAY_1, DELAY_2, DELAY_3, DELAY_4]
DET_CHS = [DET_CH1, DET_CH2, DET_CH3]

SINGLE_DET_CHS = [TRIGG_CH, *DET_CHS]
COINCIDENCE_CHS = [[TRIGG_CH, ch] for ch in DET_CHS] 
COINCIDENCE_WINDOW = 2.0