# Settings 
DELAY_1 = 0
DELAY_2 = 0
DELAY_3 = 0
DELAY_4 = 0
DELAY_5 = 30
DELAY_6 = 0
DELAY_7 = 0
DELAY_8 = 0

TRIGG_CH = 8
DET_CH1 = 1
DET_CH2 = 2
DET_CH3 = 3
DET_CH4 = 4
DET_CH5 = 5


DELAYS = [DELAY_1, DELAY_2, DELAY_3, DELAY_4, DELAY_5, DELAY_6, DELAY_7, DELAY_8]
DET_CHS = [DET_CH3]

SINGLE_DET_CHS = [TRIGG_CH, *DET_CHS]
COINCIDENCE_CHS = [[TRIGG_CH, ch] for ch in DET_CHS] 
COINCIDENCE_WINDOW = 20.0